In [5]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [8]:
a = [1,2,3,4,"hello"]
a #this is a list 

[1, 2, 3, 4, 'hello']

In [10]:
# now if i convert it into array 
np.array(a) # it gets coverted into unicode string 

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [16]:
# 2D array generation
ls=[ [1,2,3] , [4,5,6] , [6,7,8] ]
ls

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [17]:
np.array(ls)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [19]:
# array generation function
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# genearate some zeros

In [21]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [24]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.linspace(1,5,3) #linspace(start , end , how many numbers ) provide linear spacing between start to end number 

array([1., 3., 5.])

In [29]:
np.linspace(1,5) #BY default 50 equally spaced points between start and stop.

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [30]:
np.linspace(1,5,50)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [31]:
# Random number generation 
np.random.rand(5) # normalisation

array([0.08732488, 0.24751718, 0.0292377 , 0.11334005, 0.95701268])

In [32]:
np.random.randn(10) # standardisation 

array([ 0.98900239, -0.16150374, -0.1095142 ,  0.76266181, -0.64614268,
       -0.3192374 ,  0.62923975,  2.08617912,  0.83346248, -0.19808919])

In [33]:
np.random.randint(7) # single random number 

4

In [34]:
np.random.randint(10 ,20 ,10)

array([11, 13, 14, 13, 17, 13, 13, 10, 11, 18], dtype=int32)

In [37]:
#array attributes 
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr.shape

(2, 4)

In [38]:
arr.size


8

In [39]:
arr.dtype


dtype('int64')

In [44]:
#Array methods
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [56]:

print(arr.argmin()) #min element index 

0


In [48]:
print(arr.min())

1


In [49]:
print(arr.max())

9


In [50]:
print(arr.sum())

45


In [52]:
print(np.sum(arr,axis=0))#row summation

[12 15 18]


In [53]:
print(np.sum(arr,axis=1)) #col summation 

[ 6 15 24]


In [54]:
print(arr.std())#stardardisation 

2.581988897471611


In [55]:
print(arr.argmax()) #maximum element index

8


In [57]:
#reshaping and resizing 
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [58]:
arr.reshape(6,5) #6 rows and 5 columns ,convert the array into 2d array 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])