In [1]:
import numpy as np

In [2]:
#Arithmetic operations 


In [6]:
a1 = np.arange(1,11)
a2 = np.arange(11,21)

In [7]:
#addition of both array 
a1+a2

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [8]:
a1-a2

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [9]:
a1*a2

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [10]:
a1/a2

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ])

In [11]:
a1**a2

array([                  1,                4096,             1594323,
                 268435456,         30517578125,       2821109907456,
           232630513987207,   18014398509481984, 1350851717672992089,
       7766279631452241920])

In [12]:
a1//a2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
#BROADCASTING 
ls=[10,20,30,40,50]
arr = np.array(ls)#covert the list into array first 
arr

array([10, 20, 30, 40, 50])

In [15]:
arr + 10 #each element adds 10 to it 

array([20, 30, 40, 50, 60])

In [16]:
#Deep and shallow copy 
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
slice = a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [20]:
a # shallow copy 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
#deep copy 
b=a
b[0]=33
b

array([33,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
a

array([33,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
#matrix operation 
a = np.array([[1,2],[4,5]])
b = np.array([[1,2],[4,5]])

In [32]:
a

array([[1, 2],
       [4, 5]])

In [33]:
b

array([[1, 2],
       [4, 5]])

In [35]:
a @ b # matrix mul  , applicable for only square matrix 

array([[ 9, 12],
       [24, 33]])

In [37]:
np.dot(a,b) #another method

array([[ 9, 12],
       [24, 33]])

In [39]:
#transpose matrix
a.T

array([[1, 4],
       [2, 5]])

In [48]:
#advance array manipulation 

#stacking array  :use vector for stack not matrix
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [49]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [52]:
#splitting array 
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
np.hsplit(c , 2) #split the c matrix in equal 2 parts(splitting can be done on even number ) 

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [55]:
a = np.vsplit(c,4)

In [57]:
for i in a:
    print(i) # still it will be 2d array not 1 d 

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
