In [3]:
import numpy as np

In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
print(arr[6]) #indexing value on 6th index 

17


In [6]:
arr[3 : 7 : 2] #slice - arr[start , end+1,step] ,start default:0, end default :end 

array([14, 16])

In [7]:
arr[4:]

array([15, 16, 17, 18, 19, 20])

In [8]:
arr[:5]

array([11, 12, 13, 14, 15])

In [9]:
#numpy indexing and slicing of matrix 
arr= np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[0] # fetch row arr[index_row]

array([1, 2, 3, 4, 5])

In [11]:
print(arr[0,0]) #row and col 

1


In [12]:
#in the above array slice out the portion 19 , 20 , 24, 25, 29, 30
print(arr[3: ,3: ]) # arr[initial row : end row , initial col :end col]

[[19 20]
 [24 25]
 [29 30]]


In [17]:
#boolean indexing 
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [19]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])